"use client"
import { Provider } from 'react-redux'
import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import store from './store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>

      

      <body className={inter.className}>

        <Header />

        {children}
        
        <Footer />

      </body>


      </Provider>
    </html>
  )
}
